name: jasmine_eth
version: 0.0.2
description: Ethereum client SDK for Jasmine project. This SDK provides APIs to interact with Ethereum smart contracts of Jasmine Project.
homepage: https://github.com/Troublor/jasmine-eth-dart
repository: https://github.com/Troublor/jasmine-eth-dart
issue_tracker: https://github.com/Troublor/jasmine-eth-dart/issues
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  web3dart: ^1.2.3
  web_socket_channel: ^1.0.0
  http: ^0.12.2
dev_dependencies:
  test: ^1.15.4
  matcher: ^0.12.9

